WIP: Field type docs
keystonejs/keystone pull request #3306
Opened 2020-07-29 08:53 UTC by MadeByMike

For discussion.

If we plan to ship this as a blog it's probably ok. But the second half moved into my musing about current field types in a very specific way and needs to be generalised for docs.

Full of typos - will fix later :)

2020-07-29 09:05 UTC, gautamsi commented
I want to add references to contrib field and other packages,  what is best section for this. I guess new pr is needed for that.

2020-07-29 11:16 UTC, MadeByMike commented
Yeah I can do that. Let me work out where this is going to live and then I can add that in an appropriate way.

2020-08-20 07:25 UTC, molomby commented
I'd strongly suggest we put the date in the URL of the posts and probably the physical file name too (ie. `docs/blog/2020-08-03/field-types.md` or something). As we touched on today, one of the main distinguishing points between posts and the other docs is their point-in-time-ness. It's important that the age of a post be obvious. 

(It's also important we get the URLs correct up front so we don't break links later on)

2020-09-01 03:59 UTC, Noviny approved these changes

2020-09-01 04:44 UTC, timleslie requested changes

2020-09-01 04:44 UTC, timleslie commented on packages/create-keystone-app/example-projects/starter/initial-data.js
> +      _allUsersMeta: { count = 0 },
Does this change need to be in this PR? If so, we need a changeset for it.

2020-09-01 04:50 UTC, merged