Update intro-to-graphql.md
keystonejs/keystone pull request #3626
Opened 2020-09-09 16:23 UTC by zamkevich

Added explanation about search operators

2020-09-09 16:24 UTC, zamkevich commented
Looks like i don't need a changeset for docs?

2020-09-09 23:02 UTC, timleslie requested changes

2020-09-09 23:02 UTC, timleslie commented on docs/guides/intro-to-graphql.md
> +Will search the list to limit results. It can search only by [labelField](/docs/api/create-list.md#labelfield).
This isn't quite true. At the moment the `search` is applied to a `Text` field called `name`. This is not currently configurable, although that is a feature which is on our backlog.

2020-09-10 08:50 UTC, zamkevich reviewed
@timleslie I changed it to:

"For now, it can search only by `name` field. The 'name' field must be a 'Text' type."

2020-09-10 22:10 UTC, timleslie approved these changes
👍 Thanks @zamkevich, this will hopefully clear things up a bit for readers of this documentation.

2020-09-11 00:10 UTC, merged