add knex example
keystonejs/keystone pull request #3654
Opened 2020-09-14 07:33 UTC by Noviny

This PR introduces a copy of the `todo` example, but configured to use `knex` instead of `mongoose` - this is mostly being added to make keystone team developers have an easier time with their testing, but is also a good starting example for using `knex`

2020-09-14 08:29 UTC, Noviny commented
Changelog and readme need a scrub

2020-09-15 01:54 UTC, timleslie requested changes

2020-09-15 01:54 UTC, timleslie commented on examples/todo-knex/README.md
> +To run this demo project, all you need to do is run `yarn` within the Keystone project root to install all required packages, then run `yarn start todo` to begin running Keystone.
Is `yarn start todo` the right thing here?

2020-09-15 01:54 UTC, timleslie commented on examples/todo-knex/index.js
> +  adapter: new KnexAdapter({ knexOptions: { connection: 'postgres://localhost/to-do' } }),
We should give some instructions on how to create this database in the README.md

2020-09-15 03:20 UTC, Noviny commented
Good feedback. Updated readmes where relevant.

2020-09-15 03:39 UTC, timleslie approved these changes
LGTM 👍

2020-09-15 04:17 UTC, merged