Skip access control in Order create
keystonejs/keystone pull request #4450
Opened 2020-12-01 01:22 UTC by timleslie

This is for forward compatibility with upcoming changes to the items API, which will no longer skip access control by default.

2020-12-01 10:20 UTC, JedWatson requested changes

2020-12-01 10:20 UTC, JedWatson commented on examples-next/ecommerce/mutations.ts
> +        const order = await context
For the example, I'd prefer to see the context created separately from the order. I can imagine people copying+pasting this pattern and creating a new context for each items API operation, so let's clarify that into two steps.

2020-12-01 11:34 UTC, JedWatson commented on .changeset/chilled-scissors-worry.md
> +'@keystone-next/example-ecommerce': patch
Thinking about #4462, I don't think this sort of refactor is worth a changeset. It's basically duplicating the commit history for the example into the changelog. But maybe that's more accessible for people who want to follow along? I could probably be convinced if you have strong views, but I haven't been adding changesets for similar things and we should be consistent.

2020-12-01 12:01 UTC, JedWatson commented on .changeset/chilled-scissors-worry.md
> +'@keystone-next/example-ecommerce': patch
Experimented with this in #4463

2020-12-01 12:01 UTC, JedWatson commented on examples-next/ecommerce/mutations.ts
> +        const order = await context
Experimented with this in #4463

2020-12-02 22:09 UTC, timleslie commented
Superseded by #4463.

2020-12-02 22:09 UTC, closed without merging