Ability to set server PORT number via keystone config
keystonejs/keystone pull request #4669
Opened 2021-01-15 11:34 UTC by MurzNN

Comparing with #4668 - yere is another (guess better) way to fix problem with configuring server PORT number from config or `.env` file.
I move PORT assigning process from `util.ts` to start scripts, also extract config parsing from async to upper process. Hope, this is better way.

2021-02-02 22:12 UTC, timleslie requested changes
Thanks for this PR @MurzNN, I think this is the right way to go about setting the port. Just a few minor changes required. Also, could you please add a changeset with a `minor` bump to the `keystone-next/keystone` package. See the changesets bot message for instructions on how to do this (tl;dr run `yarn changeset` and follow instructions). Thanks!

2021-02-02 22:12 UTC, timleslie commented on packages-next/types/src/core.ts
> +    port?: number;
```suggestion
    /** Port number to start the server on. Defaults to process.env.PORT || 3000 */
    port?: number;
```

2021-02-02 22:12 UTC, timleslie commented on packages-next/keystone/src/scripts/run/dev.ts
>    server.listen(PORT, (err?: any) => {
```suggestion
  const port = config.server?.port || process.env.PORT || 3000;
  server.listen(port, (err?: any) => {
```

2021-02-02 22:12 UTC, timleslie commented on packages-next/keystone/src/scripts/run/start.ts
>    server.listen(PORT, (err?: any) => {
```suggestion
  const port = config.server?.port || process.env.PORT || 3000;
  server.listen(port, (err?: any) => {
```

2021-02-03 07:01 UTC, MurzNN commented
@timleslie Thanks for reviewing, I fixed all suggestions!

2021-02-03 21:18 UTC, timleslie commented on packages-next/types/src/core.ts
> +    /** Configuration options for the cors middleware. Set to true to core Keystone defaults */
```suggestion
    /** Configuration options for the cors middleware. Set to `true` to use core Keystone defaults */
```

2021-02-03 21:19 UTC, timleslie commented on .changeset/loud-singers-check.md
> +Ability to set server port number via keystone config
```suggestion
Added the ability to set the server port number via `config.server.port`.
```

2021-02-03 21:28 UTC, timleslie requested changes

2021-02-03 21:28 UTC, timleslie commented on packages-next/keystone/src/scripts/run/dev.ts
>      console.log(`⭐️ Dev Server Ready on http://localhost:${PORT}`);
```suggestion
    console.log(`⭐️ Dev Server Ready on http://localhost:${port}`);
```

2021-02-03 21:28 UTC, timleslie commented on packages-next/keystone/src/scripts/run/start.ts
>      console.log(`⭐️ Server Ready on http://localhost:${PORT}`);
```suggestion
    console.log(`⭐️ Server Ready on http://localhost:${port}`);
```

2021-02-03 21:43 UTC, timleslie approved these changes
Looks good, thanks for the contribution!

2021-02-03 21:48 UTC, merged