[WIP] Access control API docs
keystonejs/keystone pull request #4922
Opened 2021-02-22 22:20 UTC by timleslie

2021-02-23 06:52 UTC, gautamsi commented
@timleslie I wanted to remind you of condition in #3239 which was fixed in #3241, there was one condition left that it may still have incorrect sequence if user has no access to update some items (based on declarative control like isLocked = true) then the sequence in the resolveInput and afterChange would be different in the array. 

I can explain more if it does not remind you full context.

2021-02-24 02:15 UTC, timleslie commented
> @timleslie I wanted to remind you of condition in #3239 which was fixed in #3241, there was one condition left that it may still have incorrect sequence if user has no access to update some items (based on declarative control like isLocked = true) then the sequence in the resolveInput and afterChange would be different in the array.
> 
> I can explain more if it does not remind you full context.

Thanks for the reminder of these. I'm going to follow this up with a separate PR to fix that behaviour.

2021-02-24 23:53 UTC, JedWatson requested changes

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
        fieldName: text({
          access: { /* ... */ },
        }),
      },
      access: { /* ... */ },
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

afaik we call this the list **key** everywhere else

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
    }),
  }),
```

these add no value

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
      access: true,
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
          },
        }),
      },
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
        }),
      },
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
        }),
      },
    }),
  }),
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +    ListName: list({
```suggestion
    ListKey: list({
```

2021-02-24 23:53 UTC, JedWatson commented on docs-next/pages/apis/access-control.mdx
> +  /* ... */
```suggestion
        }),
      },
    }),
  }),
```

2021-02-25 00:18 UTC, JedWatson approved these changes
Nice!

2021-02-25 00:44 UTC, merged