Added domain option to session
keystonejs/keystone pull request #4951
Opened 2021-02-25 14:19 UTC by yannick1691

This adds the option for users to specify a domain for the session that is then used in the cookie.

## Use case of this feature
We ran into an issue where we had keystone running at api.domain.com, this caused the cookie domain to be set to api.domain.com.
We then had a use case for the cookie at example.domain.com, however this domain doesn't have access to the cookie.

Allowing the user to set the domain allows them to set it to: `domain.com`

This would also solve #4674 for keystone-next

2021-02-25 20:58 UTC, timleslie requested changes
Hi @yannick1691, thanks for the PR. I think this is a helpful change. To get it through could I get you to address the linting issues. I suspect it just needs trailing commas after `domain`, or you can run `yarn format`.

Also, could you please update the docs in `docs-next/pages/api/session.mdx` to include this option.

Thanks!

2021-02-26 08:59 UTC, yannick1691 commented
> 
> 
> Hi @yannick1691, thanks for the PR. I think this is a helpful change. To get it through could I get you to address the linting issues. I suspect it just needs trailing commas after `domain`, or you can run `yarn format`.
> 
> Also, could you please update the docs in `docs-next/pages/api/session.mdx` to include this option.
> 
> Thanks!

Hi @timleslie , thank you for the fast response. I have implemented the suggested changes and have updated the documentation. For the documentation I looked at the MDN specs of the domain property. I also link to the MDN page, but still mentioned some of the key parts of the domain property so that users don't miss those. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes

2021-02-28 21:42 UTC, timleslie commented on docs-next/pages/apis/session.mdx
> +  **Note** Only one domain is allowed, if a domain is specified then subdomains are always included.
```suggestion
- `domain` (default: current document URL): Host to which the cookie will be sent [Domain](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes).
  **Note** Only one domain is allowed. If a domain is specified then subdomains are always included.
```

2021-02-28 22:08 UTC, timleslie commented on docs-next/pages/apis/session.mdx
> +  **Note** Only one domain is allowed. If a domain is specified then subdomains are always included.
```suggestion
- `domain` (default: current document URL): Host to which the cookie will be sent. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#attributes) for more details on the `domain` cookie attribute..
  **Note** Only one domain is allowed. If a domain is specified then subdomains are always included.
```

2021-02-28 22:08 UTC, timleslie commented on docs-next/pages/apis/session.mdx
> +  **Note** Only one domain is allowed. If a domain is specified then subdomains are always included.
```suggestion
  **Note**: Only one domain is allowed. If a domain is specified then subdomains are always included.
```

2021-02-28 22:08 UTC, timleslie approved these changes
This looks great, thanks @yannick1691 🙏

2021-02-28 22:26 UTC, merged