Fix bug in passwordResetLink
keystonejs/keystone pull request #4965
Opened 2021-03-01 02:38 UTC by timleslie

These field names need to correspond to `const tokenType = 'passwordReset';` in `getPasswordSchemaReset.ts`. They aren't meant to be dynamic on the field name.

2021-03-01 11:58 UTC, JedWatson commented
You mean `getPasswordSchemaReset.ts`

2021-03-01 12:20 UTC, JedWatson commented
So overall I'm in favour of this, but I'd like to go more comprehensively in one direction or the other.

These fields were _supposed_ to be variable, because it's a "secret" and may not be called "password".

But can we be consistent? it's configured as a `secret` field, which is almost always called `password`, and we're hard-coding `password` in some places while it's still `secret` in others. Confusing.

I don't think I'm unhappy with this PR, since among other things it fixes a bug, but I do think I'm unhappy with the overall balance of apparently-configurable vs not-actually-configurable combined with (I think) _we use two words for the same thing_.

@timleslie if you agree, we should probably backlog another pass to clean this up properly even further, align on one consistent term, and be more opinionated overall in the name of simplicity (tbh at this point I'd go for "password" over "secret", and I think "secret" is a hangover from Keystone 5 when it genuinely was less opinionated)

(to be clear, I'm not suggesting we hard code the two primary fields - currently, `identity` and `secret` - they are defined by the list schema and only referred to here, that's fine. but you configure the "secret" field, and then we call it "password" in the context of resetting it, and that's confusing... except that devs using keystone will, if they follow the defaults / examples, see "password" and "passwordReset" columns in their database and that actually does make sense 🤦‍♂️)

2021-03-01 12:23 UTC, JedWatson requested changes

2021-03-01 12:23 UTC, JedWatson commented on .changeset/soft-stingrays-happen.md
> +'@keystone-next/auth': patch
This isn't a patch; it changes database structure for anyone using `auth` with a field path other than `password` for the secret field.

We can decide to ship this as a breaking change, or we can fix the bug in the other direction (by making `getPasswordResetSchema.ts` generate the field path dynamically based on the `secretField` config when the `tokenType` is `passwordReset`)

2021-03-01 20:57 UTC, timleslie commented on .changeset/soft-stingrays-happen.md
> +'@keystone-next/auth': patch
```suggestion
'@keystone-next/auth': major
```

2021-03-01 20:58 UTC, timleslie commented on .changeset/soft-stingrays-happen.md
> +Fixed bug when using `passwordResetLink` with a secretField other than 'password'.
```suggestion
Fixed bug when using `passwordResetLink` with a `secretField` other than 'password'. If you used a `secretField` other than `password` this change the name of the automatically generated fields, which will result in a change to your GraphQL and database schema.
```

2021-03-03 00:06 UTC, JedWatson approved these changes

2021-03-03 00:14 UTC, merged