Field/json
keystonejs/keystone pull request #5779
Opened 2021-05-24 00:19 UTC by gwyneplaine

Initial JSON field implementation:
* Simple text area ui 
* No ordering
* No filtering 

Data is converted to string for storage in sqlite, otherwise leverages the json datatype in Prisma.

2021-05-24 23:32 UTC, timleslie requested changes, later dismissed

2021-05-24 23:32 UTC, timleslie commented on .changeset/fuzzy-spiders-film.md
> +Added json field to @keystone-next/fields package.
```suggestion
Added `json` field to `@keystone-next/fields` package.
```

2021-05-24 23:32 UTC, timleslie commented on docs/pages/apis/fields.mdx
> +A `json` field represents a json blob. This is stored as a string in `sqlite`.
```suggestion
A `json` field represents a JSON blob.
```

2021-05-24 23:32 UTC, timleslie commented on examples/README.md
> +- [`json field`](./json): Using a json field to your Keystone application.
```suggestion
- [`JSON field`](./json): Using a JSON field in your Keystone application.
```

2021-05-24 23:32 UTC, timleslie commented on examples/json/README.md
> +This project demonstrates the usage of the json field.
```suggestion
This project demonstrates the usage of the `json` field type.
```

2021-05-24 23:32 UTC, timleslie commented on examples/json/README.md
> +This example implements a `Packages` list. In this field we specify a pkgjson field which is a _required_ [`json` field type](https://next.keystonejs.com/apis/fields#json).
```suggestion
This example implements a `Packages` list. In this field we specify a `pkgjson` field which is a _required_ [`json` field type](https://next.keystonejs.com/apis/fields#json).
```

2021-05-24 23:32 UTC, timleslie commented on examples/json/README.md
> +As this is required, both inputting `null` in the admin-ui as well as leaving the input empty are not accepted. However try removing the `isRequired` config option from the field config. In doing so,
```suggestion
As this is required, both inputting `null` in the Admin UI as well as leaving the input empty are not accepted. However try removing the `isRequired` config option from the field config. In doing so, you'll notice that both inputting the string `null` as well as an empty field will result in a `null` database value being stored.
```

2021-05-24 23:32 UTC, timleslie commented on examples/json/README.md
> +These projects build on this starter project and show you how to use Keystones advanced features to take your project to the next level.
```suggestion
```

2021-05-25 03:25 UTC, gwyneplaine commented on packages-next/fields/src/types/json/Implementation.ts
> +          // we store document data as a string on sqlite because Prisma doesn't support Json on sqlite
```suggestion
          // we store JSON data as a string on sqlite because Prisma doesn't support Json on sqlite
```

2021-05-25 03:49 UTC, mitchellhamilton requested changes

2021-05-25 03:49 UTC, mitchellhamilton commented on .changeset/fuzzy-spiders-film.md
> +Added `json` field to `@keystone-next/fields` package.
The user is reading a changelog in the @keystone-next/fields package so they already know where it's been added to.

```suggestion
Added `json` field.
```

2021-05-25 03:49 UTC, mitchellhamilton commented on packages-next/fields/src/types/json/views/index.tsx
> +        parsedValue = undefined;
This is doing nothing
```suggestion
```

2021-05-25 03:53 UTC, mitchellhamilton requested changes

2021-05-25 03:53 UTC, mitchellhamilton commented on packages-next/fields/src/types/json/index.ts
> +    };
Let's not have this since you can't change it, if we can let you customise it in the future, we can add it then

2021-05-25 03:59 UTC, mitchellhamilton commented on packages-next/fields/src/types/json/index.ts
> +    defaultValue?: FieldDefaultValue<string>;
This should be any json value, right? (I think we have a type for that in @keystone-next/types)

2021-05-25 04:02 UTC, mitchellhamilton commented on packages-next/fields/src/types/json/views/index.tsx
> +type Config = FieldControllerConfig<{ displayMode: 'input' | 'textarea' }>;
```suggestion
type Config = FieldControllerConfig
```

2021-05-25 05:29 UTC, mitchellhamilton approved these changes

2021-05-25 05:44 UTC, merged