Move packages-next to packages
keystonejs/keystone pull request #6087
Opened 2021-07-12 12:00 UTC by JedWatson

Been meaning to do this since we got rid of the last legacy packages and removed the original `packages` directory.

This moves `packages-next` to `packages` and updates all the references.

I also found a few things we missed (old config in `package.json` etc) for things that have been removed, and cleaned it up.

2021-07-12 23:23 UTC, timleslie requested changes
Requires a changeset

2021-07-13 00:12 UTC, JedWatson commented
@timleslie

> Requires a changeset

What were you expecting this to include?

2021-07-13 00:36 UTC, timleslie commented on .changeset/early-dingos-retire.md
> +Move packages-next to packages
```suggestion
Move source code from the `packages-next` to the `packages` directory.
```

2021-07-13 00:48 UTC, timleslie commented on .changeset/early-dingos-retire.md
> +---
```suggestion
"@keystone-next/cloudinary": patch
"@keystone-next/document-renderer": patch
"@keystone-next/fields": patch
"@keystone-next/fields-document": patch
"@keystone-next/keystone": patch
"@keystone-next/session-store-redis": patch
"@keystone-next/testing": patch
"@keystone-next/types": patch
"@keystone-next/utils": patch
"@keystone-next/api-tests-legacy": patch
---
```

Need to ship patch releases for all the packages which have changed their package.json files.

2021-07-13 01:10 UTC, timleslie approved these changes
👍

2021-07-13 01:15 UTC, merged