Nested filters
keystonejs/keystone pull request #6095
Opened 2021-07-13 05:23 UTC by mitchellhamilton

This is very draft right now and is just a translation of Prisma's filters into GraphQL

2021-08-10 23:22 UTC, timleslie requested changes

2021-08-10 23:22 UTC, timleslie commented on yarn.lock
> +
```suggestion
```

2021-08-10 23:22 UTC, timleslie commented on yarn.lock
> +
```suggestion
```

2021-08-11 11:07 UTC, gautamsi commented
Can this new filter support `null` or `not null` value in UI? I guess we would need it for most nullable fields

2021-08-12 04:01 UTC, mitchellhamilton commented
> Can this new filter support null or not null value in UI? I guess we would need it for most nullable fields

With this PR, the filters in the Admin UI will behave the same as they do currently, we're planning to revamp the filter UI which will handle null properly among other things but that's not happening in this PR

2021-08-12 04:17 UTC, timleslie approved these changes
Looking good 👍

2021-08-12 04:17 UTC, merged