Examples custom nav guide
keystonejs/keystone pull request #6185
Opened 2021-07-26 00:52 UTC by gwyneplaine

Guide and example for #6111 
Split out for expedited functional release.

2021-07-28 05:30 UTC, gwyneplaine commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +### Components
Honestly this is definitely not the right place for *this* kind of documentation. 

Very much taking a 'let's get this content in first and figure out where it goes later' approach here.

2021-07-28 12:03 UTC, JedWatson commented on docs/components/docs/ExamplesList.tsx
> +        heading="Custom Admin-UI Navigation"
```suggestion
        heading="Custom Admin UI Navigation"
```

2021-07-28 12:04 UTC, JedWatson commented on docs/components/docs/ExamplesList.tsx
> +        heading="Custom Admin-UI Navigation"
For consistency with other navigation items:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/872310/127319155-48f62ac5-5faa-4c63-8549-1b47527d8343.png">

2021-07-29 00:44 UTC, JedWatson requested changes

2021-07-29 00:44 UTC, JedWatson commented on docs/components/docs/Navigation.tsx
> +          Custom Admin-UI Navigation <Badge look="success">New</Badge>
```suggestion
          Custom Admin UI Navigation <Badge look="success">New</Badge>
```

For consistency with other nav items

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +In this guide, we'll illustrate how to create a custom Navigation component with custom routes to be rendered in the Admin-UI.
```suggestion
In this guide, we'll show you how to create a custom Navigation component with custom routes to be rendered in the Admin-UI.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +!> `NavigationContainer` is one of many assistive components to help you more easily compose your custom Navigation component. You can read more about it down [below](#components).
```suggestion
!> `NavigationContainer` is one of several higher-level components to help you more easily compose your custom Navigation component. You can read more about it down [below](#components).
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +This should be handled for you automatically by passing the prop into the `NavigationContainer`,
```suggestion
The `authenticatedItem` props is rendered automatically when you pass it into the `NavigationContainer` component.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +?> If you wish to render out the `authenticatedItem` in a custom manner, please be aware that you will need to handle all of the possible states of the `authenticatedItem`. Explaining how to do this
```suggestion
?> If you render the `authenticatedItem` yourself, make sure you handle all of the possible states.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +Keystone exposes a variety of helper components to make building out your custom Admin-UI Navigation component easier. These are:
```suggestion
Keystone exposes a variety of helper components to make building out your custom Admin UI Navigation component easier. These are:
```

"Admin UI" is never "Admin-UI"

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +This is component renders containing markup around your routes, as well as as the different stats of the authenticatedItem prop.
```suggestion
This component renders containing markup around your navigation links, as well as as the different states of the `authenticatedItem` prop.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +This component takes the provided Array of `lists` and renders out a list of NavItems.
```suggestion
This component takes the provided Array of `lists` and renders a list of NavItems.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +```
This seems incorrect, maybe from an older version of the API?

The "routes object" isn't actually mentioned above (the concept of routes is) and these are just props, per the example below.

Better to express this (and the two types below) as describing props:

```suggestion
The `ListNavItems` component takes the following props:

```typescript
type ListNavProps = {
  lists: ListMeta[];
  include: string[];
}
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +The impetus behind `ListNavItem` is to have a higher-level abstraction that can allow users to not have to care about the contents and structure of our lists.
```suggestion
The idea behind `ListNavItem` is to have a higher-level abstraction that makes it easier to render navigation links for lists consistently.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +This is especially relevant for future feature additions to the nav. (i.e. if we add icon support, that would work out of the box from a dependency bump for users of ListNavItem, whereas you'd have t
```suggestion
This is especially relevant for future feature additions to the nav. (i.e. if we add icon support, that would work out of the box from a dependency bump for users of ListNavItem, whereas you'd have to add that icon prop manually with a lower level component.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +a) Has the styling constraints of the default Admin-UI navigation
```suggestion
a) Has the styling constraints of the default Admin UI navigation
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +but would still like to not have to care about which list properties need to be associated with each NavItem prop.
```suggestion
but would still like to not have to worry about which list properties need to be associated with each NavItem prop.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +d) Renders out additional UI based on whether or not the user has signed in provided by the `authenticatedItem` prop.
```suggestion
d) Renders additional UI based on whether or not the user has signed in provided by the `authenticatedItem` prop.
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +## Adding the custom navigation component to the Admin-UI
```suggestion
## Adding the custom navigation component to the Admin UI
```

2021-07-29 00:44 UTC, JedWatson commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +Keystone is made aware of custom components it needs to render in the Admin-UI via the `/admin/config.ts` file in your project root.
```suggestion
Keystone is made aware of custom components it needs to render in the Admin UI via the `/admin/config.ts` file in your project root.
```

2021-07-29 00:44 UTC, JedWatson commented on examples/custom-admin-ui-navigation/README.md
> +This project demonstrates how to create a custom Navigation component for use in the Admin-UI. It builds on the [Task Manager](../task-manager) starter project.
```suggestion
This project demonstrates how to create a custom Navigation component for use in the Admin UI. It builds on the [Task Manager](../task-manager) starter project.
```

2021-07-29 01:23 UTC, JedWatson submitted a review, later dismissed

2021-07-29 01:23 UTC, JedWatson commented on examples/custom-admin-ui-navigation/README.md
> +## Feature Example - Custom Field View
This heading isn't right, this is the Admin UI Navigation example

2021-07-30 02:22 UTC, timleslie requested changes

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +`lists` is an array of keystone list objects. Internally Keystone filters through your lists and ensures that only visible lists are passed through to you in the `lists` array prop.
```suggestion
`lists` is an array of Keystone list objects. Internally Keystone filters through your lists and ensures that only visible lists are passed through to you in the `lists` array prop.
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +Use this component when you want to have more granular control over rendering nav items from lists prop provided to the `Navigation` component by keystone,
```suggestion
Use this component when you want to have more granular control over rendering nav items from lists prop provided to the `Navigation` component by Keystone,
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +export  const component: AdminConfig['components'] = {
```suggestion
import { CustomNavigation } from './components/CustomNavigation';

export const component: AdminConfig['components'] = {
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +import type { AdminConfig } from '@keystone-next/types';
```suggestion
```ts
// /admin/config.ts
import type { AdminConfig } from '@keystone-next/types';
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +```
```suggestion
```

This info isn't really helpful at this stage. We can just show them what to put in file, they can worry about typescript later.

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +The first thing you'll need to do in creating your custom Navigation component is to specify an `/admin/config.ts` file in the root of your Keystone project.
```suggestion
The first thing you'll need to do is to specify an `/admin/config.ts` file in the root of your Keystone project.
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +Reference your custom Navigation component in the export as so, the exported component can either be declared inline or imported from elsewhere in your project.
```suggestion
Reference your custom Navigation component in the export as so.
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +export function CustomNavigation({ authenticatedItem, lists }: NavigationProps) {
Let's add the appropriate `NavigationProps` import to this snippet, and also include a filename comment at the top for consistency.

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +If it detects a Navigation property in the `config.tsx` file we created earlier, Keystone will pass the following props to this component.
```suggestion
Keystone will pass the following props to this component.
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +The `NavigationContainer` component renders containing markup around your navigation links, as well as as the different states of the `authenticatedItem` prop. We'll need this to:
```suggestion
The `NavigationContainer` component provides a container around your navigation links, as well as the different states of the `authenticatedItem` prop. We'll need this to:
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +The `NavItem` component is a thin styling and accessibility wrapper around the Link component from Next.js. We'll use this component to render out custom route as well as the `Dashboard` route that K
```suggestion
The `NavItem` component is a thin styling and accessibility wrapper around the Link component from Next.js. We'll use this component to render our custom route as well as the `Dashboard` route.
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +?> **Note** When opting into a custom Navigation component you will need to specify a NavItem for the `Dashboard` page (the index route). Keystone doesn't provide this to you out of the box, as it's
```suggestion
?> **Note** When opting into a custom Navigation component you will need to specify a NavItem for the `Dashboard` page (the `/` route).
```

2021-07-30 02:22 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +With all that done, your Custom Navigation component should be good to go, and your admin folder should look like this.
```suggestion
With all that done, your Custom Navigation component should be good to go, and your `/admin` folder should look like this.
```

2021-07-30 03:30 UTC, timleslie requested changes

2021-07-30 03:30 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +Here we'll export our CustomNavigation component as a named export.
```suggestion
Here we'll export our `CustomNavigation` component as a named export.
```

2021-07-30 03:30 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +      <NavItem href="/">Dashboard<NavItem>
```suggestion
      <NavItem href="/">Dashboard</NavItem>
```

2021-07-30 03:30 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +};
This should be exporting the value, not the type.

2021-07-30 04:10 UTC, timleslie requested changes

2021-07-30 04:10 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +This component takes the provided Array of `lists` and renders a list of `NavItems`.
```suggestion
This component takes the provided array of `lists` and renders a list of `NavItems`.
```

2021-07-30 04:10 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +If an include prop is supplied, the component will only render out lists that match the list `keys` specified in the include array.
```suggestion
If an `include` prop is supplied, the component will only render out lists that match the list `keys` specified in the `include` array.
```

2021-07-30 04:10 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +As mentioned above the lists object has the following type:
```suggestion
The `lists` object has the following type:
```

2021-07-30 04:31 UTC, timleslie requested changes

2021-07-30 04:31 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +        KeystoneJS Docs
```suggestion
        Keystone Docs
```

2021-07-30 04:31 UTC, timleslie commented on docs/pages/docs/guides/custom-admin-ui-navigation.mdx
> +        KeystoneJS Docs
```suggestion
        Keystone Docs
```

2021-07-30 04:34 UTC, timleslie approved these changes
Let's 🚢 it!

2021-07-30 04:41 UTC, merged