Respect graphql.omit in fieldMode resolvers
keystonejs/keystone pull request #6429
Opened 2021-08-30 02:29 UTC by timleslie

2021-08-30 23:12 UTC, mitchellhamilton requested changes
We need to either have a static fieldMode that signals "never fetch this" for the itemView or fetch the fieldModes and _then_ do the item query otherwise the whole query will be invalid (i would prefer the former)

2021-08-30 23:47 UTC, timleslie commented
> We need to either have a static fieldMode that signals "never fetch this" for the itemView or fetch the fieldModes and _then_ do the item query otherwise the whole query will be invalid (i would prefer the former)

Yeah, so that's definitely on the todo list for today, but I want to do it separate to this particular change, as it's going to require a more complex solution than these low-hanging fixes which need to go through.

2021-08-31 00:01 UTC, mitchellhamilton commented on packages/keystone/src/admin-ui/system/createAdminMeta.ts
> -      if (field.access.read === false) continue;
Could you add this back(but based on isEnabled) until we deal with this properly then?

2021-08-31 06:27 UTC, mitchellhamilton commented on packages/keystone/src/admin-ui/system/createAdminMeta.ts
> +      if (field.access.read === false) continue;
I meant check `graphql.isEnabled` here and exclude it if read is disabled

2021-08-31 07:04 UTC, mitchellhamilton approved these changes

2021-08-31 07:05 UTC, merged