[WIP] ga-release prep
keystonejs/keystone pull request #7005
Opened 2021-11-29 00:26 UTC by gwyneplaine

replace `@keystone-next` with `@keystone-6` in preparation for namespace change

2021-11-29 04:43 UTC, raveling commented on README.md
> +It's currently in the final stages of preview release, and published on npm under the `@keystone-6` namespace. To learn more, check out our [Roadmap page](https://keystonejs.com/updates/roadmap).
```suggestion
Keystone 6 is published on npm under the `@keystone-6` namespace. To learn about where we’re taking Keystone check out our [Roadmap](https://keystonejs.com/updates/roadmap).
```

2021-11-30 02:01 UTC, mitchellhamilton approved these changes

2021-11-30 02:01 UTC, dcousens approved these changes
Go

2021-11-30 02:01 UTC, gwyneplaine commented
LGTM

2021-11-30 02:01 UTC, bladey approved these changes

2021-11-30 02:02 UTC, JedWatson approved these changes
Let's Gooooo 🚀

2021-11-30 02:37 UTC, dcousens requested changes
Tests failing,  holding until tomorrow + resolved

2021-11-30 04:30 UTC, dcousens approved these changes

2021-11-30 04:58 UTC, merged