fix api types
keystonejs/keystone pull request #7073
Opened 2021-12-12 18:32 UTC by SerWonka

import changed in articaft.ts from KeystoneListsTypeInfo to Lists since KeystoneListsTypeInfo is no longer in types (changes in https://github.com/keystonejs/keystone/pull/7001)

2021-12-15 00:26 UTC, dcousens commented on .changeset/gentle-paws-cough.md
> +import changed in articaft.ts from KeystoneListsTypeInfo to Lists since KeystoneListsTypeInfo is no longer in types (changes in https://github.com/keystonejs/keystone/pull/7001)
```suggestion
Fix Lists import in artifacts types (changed in https://github.com/keystonejs/keystone/pull/7001)
```

2021-12-15 00:40 UTC, mitchellhamilton requested changes
Could you change it to this? (It's possible to write it with `KeystoneListsAPI` but this is easier)

```ts
import { Context } from './types';

export const query: Context['query'];
```

The `Lists` type is for the list configs, it isn't the type info

2021-12-21 03:11 UTC, dcousens commented on packages/keystone/src/scripts/tests/artifacts.test.ts
> +      export const query: KeystoneListsAPI<Lists>;
```suggestion
      export const query: Context['query'];
```

2021-12-21 03:11 UTC, dcousens commented on packages/keystone/src/scripts/tests/artifacts.test.ts
> +      import { Lists } from './types';
```suggestion
      import { Context } from './types';
```

2021-12-21 03:14 UTC, dcousens commented on packages/keystone/src/artifacts.ts
> +export const query: KeystoneListsAPI<Lists>;`;
```suggestion
export const query: Context['query'];
```

2021-12-21 03:14 UTC, dcousens commented on packages/keystone/src/artifacts.ts
> +import { Lists } from './types';
```suggestion
import { Context } from './types';
```

2021-12-21 03:18 UTC, dcousens commented on packages/keystone/src/artifacts.ts
> +export const query: Context['query'];
```suggestion
export const query: Context['query'];`;
```

2021-12-21 03:34 UTC, dcousens approved these changes

2021-12-21 03:45 UTC, merged