Add acl option for s3 storage
keystonejs/keystone pull request #8264
Opened 2023-01-19 19:27 UTC by jhohlfeld

This PR adds ACL settings to the s3 storage config.

## Why

This change was necessary because on DigitalOcean I wasn't able to see my uploaded images publicly. Instead, I had to set them to public manually. 

DO does not let you set default permissions:
https://docs.digitalocean.com/products/spaces/how-to/set-file-permissions/

> By default, file permissions are set to Private. Some third-party tools provide support for changing the default permissions, but there is currently no way to do so in the control panel.

## Usage

```typescript
config({
  storage: {
    remote: {
      kind: 's3',
      type: 'image',
      bucketName,
      region,
      accessKeyId,
      secretAccessKey,
      endpoint,

      /** Optionally add one of the ACL options from AWS-SDK.
       * 
       * Example: 'private', 'public-read' or 'public-read-write'.
       * 
       * See https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
       * for more details.
       */
      acl: 'public-read'
    },    
  }
});
```

2023-01-20 00:41 UTC, dcousens commented
Nice pull request @jhohlfeld!
I'm trying to determine if any part of this should be captured as part of the field type or individually for uploads; but maybe that's a different use-case that we can leave out and move forward with this as-is.

2023-01-24 04:48 UTC, borisno2 requested changes
Looks good, thanks @jhohlfeld 
Just a couple of website fixes needed so that the docs don't update until this change is ~deployed~ released.
Thanks,

2023-01-24 10:29 UTC, dcousens commented on docs/pages/docs/config/config.md
> +  - `'private'` No public assess.
```suggestion
  - `'private'` No public access.
```

2023-01-26 01:53 UTC, borisno2 approved these changes

2023-01-26 02:40 UTC, merged